export const ErrorCodeEnum = {
  ALL_FIELDS_REQUIRED: "ALL_FIELDS_REQUIRED",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  NOT_FOUND: "NOT_FOUND",
  INVALID_SLUG: "INVALID_SLUG",

  // AUTH-related error codes
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_NOT_FOUND: "AUTH_NOT_FOUND",
  AUTH_TOO_MANY_ATTEMPTS: "AUTH_TOO_MANY_ATTEMPTS",
  AUTH_UNAUTHORIZED_ACCESS: "AUTH_UNAUTHORIZED_ACCESS",
  AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",

  // ACCESS-related error codes
  ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",

  // Validation-related error codes
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // RESOURCE-related error codes (generic or specific resources)
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND", // You can extend this for specific resources like 'PRODUCT_NOT_FOUND'

  // Internal server error
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  // Product-related error codes (example)
  PRODUCTS_NOT_FOUND: "PRODUCTS_NOT_FOUND",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  PRODUCT_CREATE_FAILED: "PRODUCT_CREATE_FAILED",
  PRODUCT_UPDATE_FAILED: "PRODUCT_UPDATE_FAILED",
} as const;

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum;
